alias r='./bin/rails'
alias rs='./bin/rails server -b 0.0.0.0'
alias rdm='./bin/rails db:migrate'
alias rdr='./bin/rails db:reset'
alias rc='./bin/rails console'

alias gs='git status'
alias ga='git add .'
alias gc='git commit -m'
alias gac='git add . && git commit -m'
alias gp='git push'
